### ISSUE TITLE
No longer works (11.10.2022)

### ISSUE THREAD

**Issue by altoid29** [sneakyevilSK/VAC-Error-Fixerino#1]
Attempted on CS:GO, seems to no longer be working.

- Tried with steam closed.
- Tried with steam open.
- Tried with CS:GO open.

"VAC was unable to verify your game session."

**Comment by sneakyevilSK** [comment]
This is old crap I wrote no idea how it even works, don't care to be honest about it. You should be fine just manually running steamservice.exe /repair in steam/bin folder and checking if steamservice even runs while steam is opened.
